// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

import mfe0 from '@/mfe_packages/enrichments-mfe/mfe.src.json';

import type { Extension, JSONSchema, MfeEntry } from '@cyberfabric/react';

export interface MfeManifestConfig {
  manifest: JSONSchema;
  entries: MfeEntry[];
  extensions: Extension[];
}

export const MFE_MANIFESTS: MfeManifestConfig[] = [
  mfe0,
];

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
